### ISSUE TITLE
Strings not scanned with WP 4.4.2 and Timber 0.22.5

### ISSUE THREAD

**Issue by matteopoile** [marcinkazmierski/Polylang---theme-translation#1]
I've got this code:
`pll_e('newsletter.CTA');
pll__('newsletter.CTA');
`
in template-home.php in the root of my active theme but it doesn't show on settings > languages > string translations.

Furthermore I can't understand how to use the plugin directly in twig files, i tried:
`{{ ppl__('newsletter.CTA') }}`

but got this error:

Fatal error: Uncaught exception 'Twig_Error_Syntax' with message 'Unknown "ppl__" function in "components/newsletter.twig" at line 4.' in D:\Lavoro\web\www\1601.factoryforhome.it\project\wp-content\plugins\timber-library\vendor\twig\twig\lib\Twig\ExpressionParser.php:573 Stack trace: #0 D:\Lavoro\web\www\1601.factoryforhome.it\project\wp-content\plugins\timber-library\vendor\twig\twig\lib\Twig\ExpressionParser.php(351): Twig_ExpressionParser->getFunctionNodeClass('ppl__', 4) #1 D:\Lavoro\web\www\1601.factoryforhome.it\project\wp-content\plugins\timber-library\vendor\twig\twig\lib\Twig\ExpressionParser.php(144): Twig_ExpressionParser->getFunctionNode('ppl__', 4) #2 D:\Lavoro\web\www\1601.factoryforhome.it\project\wp-content\plugins\timber-library\vendor\twig\twig\lib\Twig\ExpressionParser.php(84): Twig_ExpressionParser->parsePrimaryExpression() #3 D:\Lavoro\web\www\1601.factoryforhome.it\project\wp-content\plugins\timber-library\vendor\twig\twig\lib\Twig\ExpressionParser.php(41): Twig_ExpressionParser->getPrimary() #4 D:\L in D:\Lavoro\web\www\1601.factoryforhome.it\project\wp-content\plugins\timber-library\vendor\twig\twig\lib\Twig\ExpressionParser.php on line 573

**Comment by marcinkazmierski** [comment]
Please use this in twig files:
`{{ pll_e('text') }}` or `{{ pll__('text') }}`
not this: `ppl__()`  -> typo...
:)

Next on the timber context you must declare this functions like:

```
  $context['pll_e'] = TimberHelper::function_wrapper('pll_e');
  $context['pll_'] = TimberHelper::function_wrapper('pll_');
```

See more on:
http://upstatement.com/timber/

Is everything clear?

**Comment by matteopoile** [comment]
Thanks a lot, It works!
I tried 
`{{ pll_e('text') }} or {{ pll__('text') }}`
without adding the functions to $context

**Comment by leo-cheron** [comment]
You should definitely add this smart trick to your readme file.
