### ISSUE TITLE
String capture not working properly if translation function contains translation domain

### ISSUE THREAD

**Issue by indrek-k** [marcinkazmierski/Polylang---theme-translation#5]
Hi there!

It seems that when a translation text domain is added to the translation function, the regex doesn't properly capture only the translatable string, but also captures the domain. See attached example screenshot:

![regex](https://user-images.githubusercontent.com/1229164/43414293-0839385e-943b-11e8-9284-462c0e36c759.PNG)

(Yes, the same problem exists in WP admin).

Apologies for not being able to submit a fix, I suck at regex. And thanks for the excellent plugin!

**Comment by marcinkazmierski** [comment]
Hi,
this char is not supported by PHP for strings:
`
I think it is not a problem :) 
http://sandbox.onlinephpfunctions.com/

**Comment by indrek-k** [comment]
Thanks so much for your quick reply!

We're not using that char in our codebase - it's an artifact from the online regex tester. 
Here's the original line of code that's causing trouble:
```php
{!! previous_post_link('%link', pll__('Next', 'domain') . ' &raquo;') !!}
```

Try it yourself!

**Comment by marcinkazmierski** [comment]
Hi,
I agree with you for this example, but function pll__() require one parameter:
https://polylang.wordpress.com/documentation/documentation-for-developers/functions-reference/
With one parameter everything works fine.

**Comment by indrek-k** [comment]
Of course, the textdomain is not required here...

My bad. Thanks so much for the clarification!
